<?php

namespace Database\Seeders;

use App\Models\Spell;
use App\Models\SpellSchool;
use App\Models\SpellType;

class SpellSeeder extends ResourceSeeder
{
    public function run()
    {
        $this->createSchools([
            'Abjuration',
            'Conjuration',
            'Conjuration',
            'Divination',
            'Enchantment',
            'Evocation',
            'Illusion',
            'Necromancy',
            'Transmutation',
        ]);

        $this->createTypes([
            '1st Level',
            '2nd Level',
            '3rd Level',
            '4th Level',
            '5th Level',
            '6th Level',
            '7th Level',
            '8th Level',
            '9th Level',
            'Cantrip',
        ]);

        $this->create([
            'Blade Ward' => [ 'school' => 'abjuration', 'type' => 'cantrip' ],
            'Zephyr Strike' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Self' ],
            'Wind Walk' => [ 'type' => '6th-level', 'time' => '1 Minute', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Water Walk' => [ 'type' => '3rd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Water Breathing' => [ 'type' => '3rd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'True Polymorph' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Transmute Rock' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Tiny Servant' => [ 'type' => '3rd-level', 'time' => '1 Minute', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Time Stop' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Thorn Whip' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Thaumaturgy' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            "Tenser's Transformation" => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Temporal Shunt' => [ 'type' => '5th-level', 'time' => 'Reaction', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Telekinesis' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Swift Quiver' => [ 'type' => '5th-level', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Stone Shape' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Spike Growth' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '150 feet' ],
            'Spider Climb' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Speak with Plants' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self (30-foot radius)' ],
            'Slow' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Skywrite' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Sight' ],
            'Skill Empowerment' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Shillelagh' => [ 'type' => 'cantrip', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Shapechange' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Shape Water' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Sequester' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Rope Trick' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Reverse Gravity' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '100 feet' ],
            'Reincarnate' => [ 'type' => '5th-level', 'time' => '1 Hour', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Regenerate' => [ 'type' => '7th-level', 'time' => '1 Minute', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Pyrotechnics' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Purify Food and Drink' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'transmutation', 'range' => '10 feet' ],
            'Primal Savagery' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Prestidigitation' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '10 feet' ],
            'Polymorph' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Plant Growth' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '150 feet' ],
            'Passwall' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Move Earth' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Mold Earth' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Message' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Mending' => [ 'type' => 'cantrip', 'time' => '1 Minute', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Meld into Stone' => [ 'type' => '3rd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            "Maximilian's Earthen Grasp" => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Mass Polymorph' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Magnify Gravity' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Magic Weapon' => [ 'type' => '2nd-level', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Magic Stone' => [ 'type' => 'cantrip', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Longstrider' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Lightning Arrow' => [ 'type' => '3rd-level', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Self' ],
            'Levitate' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Knock' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Jump' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Investiture of Wind' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Investiture of Stone' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Investiture of Ice' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Investiture of Flame' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Immovable Object' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Heat Metal' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Haste' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Gust' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Guardian of Nature' => [ 'type' => '4th-level', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Self' ],
            'Goodberry' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Glibness' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Giant Insect' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Gaseous Form' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Fly' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Flesh to Stone' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Flame Arrows' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Feather Fall' => [ 'type' => '1st-level', 'time' => 'Reaction', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Fabricate' => [ 'type' => '4th-level', 'time' => '10 Minutes', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Expeditious Retreat' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Self' ],
            'Etherealness' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Erupting Earth' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Enlarge/Reduce' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Enhance Ability' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Elemental Weapon' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Elemental Bane' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '90 feet' ],
            'Earthbind' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '300 feet' ],
            'Druidcraft' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            "Dragon's Breath" => [ 'type' => '2nd-level', 'time' => 'Bonus acn.', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Disintegrate' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Darkvision' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Create or Destroy Water' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Create Magen' => [ 'type' => '7th-level', 'time' => '1 Hour', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Create Homunculus' => [ 'type' => '6th-level', 'time' => '1 Hour', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Cordon of Arrows' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '5 feet' ],
            'Control Winds' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '300 feet' ],
            'Control Weather' => [ 'type' => '8th-level', 'time' => '10 Minutes', 'school' => 'transmutation', 'range' => 'Self (5-mile radius)' ],
            'Control Water' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '300 feet' ],
            'Control Flames' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Catapult' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '60 feet' ],
            'Bones of the Earth' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Blink' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Barkskin' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Awaken' => [ 'type' => '5th-level', 'time' => '8 Hours', 'school' => 'transmutation', 'range' => 'Touch' ],
            'Animate Objects' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '120 feet' ],
            'Animal Shapes' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => '30 feet' ],
            'Alter Self' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'transmutation', 'range' => 'Self' ],
            'Vampiric Touch' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Self' ],
            'True Resurrection' => [ 'type' => '9th-level', 'time' => '1 Hour', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Toll the Dead' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Time Ravage' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '90 feet' ],
            'Tether Essence' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Speak with Dead' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '10 feet' ],
            'Spare the Dying' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Soul Cage' => [ 'type' => '6th-level', 'time' => 'Reaction', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Shadow of Moil' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Self' ],
            'Sapping Sting' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'necromancy', 'range' => '30 feet' ],
            'Revivify' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Resurrection' => [ 'type' => '7th-level', 'time' => '1 Hour', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Ray of Sickness' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Ray of Enfeeblement' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Raise Dead' => [ 'type' => '5th-level', 'time' => '1 Hour', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Negative Energy Flood' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Magic Jar' => [ 'type' => '6th-level', 'time' => '1 Minute', 'school' => 'necromancy', 'range' => 'Self' ],
            'Life Transference' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '30 feet' ],
            'Inflict Wounds' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Harm' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Gentle Repose' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Finger of Death' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Feign Death' => [ 'type' => '3rd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Touch' ],
            'False Life' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Self' ],
            'Eyebite' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Self' ],
            'Enervation' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Danse Macabre' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Create Undead' => [ 'type' => '6th-level', 'time' => '1 Minute', 'school' => 'necromancy', 'range' => '10 feet' ],
            'Contagion' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Clone' => [ 'type' => '8th-level', 'time' => '1 Hour', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Circle of Death' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '150 feet' ],
            'Chill Touch' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'necromancy', 'range' => '120 feet' ],
            'Cause Fear' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '60 feet' ],
            'Blindness/Deafness' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '30 feet' ],
            'Blight' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '30 feet' ],
            'Bestow Curse' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => 'Touch' ],
            'Astral Projection' => [ 'type' => '9th-level', 'time' => '1 Hour', 'school' => 'necromancy', 'range' => '10 feet' ],
            'Animate Dead' => [ 'type' => '3rd-level', 'time' => '1 Minute', 'school' => 'necromancy', 'range' => '10 feet' ],
            "Abi-Dalzim's Horrid Wilting" => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'necromancy', 'range' => '150 feet' ],
            'Weird' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '120 feet' ],
            'Simulacrum' => [ 'type' => '7th-level', 'time' => '12 Hours', 'school' => 'illusion', 'range' => 'Touch' ],
            'Silent Image' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '60 feet' ],
            'Silence' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'illusion', 'range' => '120 feet' ],
            'Shadow Blade' => [ 'type' => '2nd-level', 'time' => 'Bonus acn.', 'school' => 'illusion', 'range' => 'Self' ],
            'Seeming' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '30 feet' ],
            'Project Image' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '500 miles' ],
            'Programmed Illusion' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '120 feet' ],
            'Phantom Steed' => [ 'type' => '3rd-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'illusion', 'range' => '30 feet' ],
            'Phantasmal Killer' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '120 feet' ],
            'Phantasmal Force' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '60 feet' ],
            "Nystul's Magic Aura" => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Touch' ],
            'Mislead' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Self' ],
            'Mirror Image' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Self' ],
            'Mirage Arcane' => [ 'type' => '7th-level', 'time' => '10 Minutes', 'school' => 'illusion', 'range' => 'Sight' ],
            'Minor Illusion' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'illusion', 'range' => '30 feet' ],
            'Mental Prison' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '60 feet' ],
            'Major Image' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '120 feet' ],
            'Magic Mouth' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'illusion', 'range' => '30 feet' ],
            'Invisibility' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Touch' ],
            'Illusory Script' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'illusion', 'range' => 'Touch' ],
            'Illusory Dragon' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '120 feet' ],
            'Hypnotic Pattern' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'illusion', 'range' => '120 feet' ],
            'Hallucinatory Terrain' => [ 'type' => '4th-level', 'time' => '10 Minutes', 'school' => 'illusion', 'range' => '300 feet' ],
            'Greater Invisibility' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Touch' ],
            'Fear' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Self (30-foot cone)' ],
            'Dream' => [ 'type' => '5th-level', 'time' => '1 Minute', 'school' => 'illusion', 'range' => 'Special' ],
            'Distort Value' => [ 'type' => '1st-level', 'time' => '1 Minute', 'school' => 'illusion', 'range' => 'Touch' ],
            'Disguise Self' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Self' ],
            'Creation' => [ 'type' => '5th-level', 'time' => '1 Minute', 'school' => 'illusion', 'range' => '30 feet' ],
            'Color Spray' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Self (15-foot cone)' ],
            'Blur' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'illusion', 'range' => 'Self' ],
            'Wrathful Smite' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Self' ],
            'Wrath of Nature' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Word of Radiance' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '5 feet' ],
            'Witch Bolt' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '30 feet' ],
            'Wind Wall' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Whirlwind' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '300 feet' ],
            'Warding Wind' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self' ],
            'Wall of Water' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Wall of Stone' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Wall of Sand' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '90 feet' ],
            'Wall of Light' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Wall of Ice' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Wall of Force' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Wall of Fire' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Vitriolic Sphere' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Thunderwave' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (15-foot cube)' ],
            'Thunderous Smite' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Self' ],
            'Thunderclap' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '5 feet' ],
            'Telepathy' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Unlimited' ],
            'Sunburst' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Sunbeam' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (60-foot line)' ],
            'Storm Sphere' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Staggering Smite' => [ 'type' => '4th-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Self' ],
            'Spiritual Weapon' => [ 'type' => '2nd-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => '60 feet' ],
            "Snilloc's Snowball Swarm" => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '90 feet' ],
            'Sickening Radiance' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Shocking Grasp' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Touch' ],
            'Shatter' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Sending' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Unlimited' ],
            'Searing Smite' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Self' ],
            'Scorching Ray' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Sacred Flame' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Ray of Frost' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Ravenous Void' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '1000 feet' ],
            'Pulse Wave' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (30-foot cone)' ],
            'Prismatic Spray' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (60-foot cone)' ],
            'Prayer of Healing' => [ 'type' => '2nd-level', 'time' => '10 Minutes', 'school' => 'evocation', 'range' => '30 feet' ],
            'Power Word Heal' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Touch' ],
            "Otiluke's Resilient Sphere" => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '30 feet' ],
            "Otiluke's Freezing Sphere" => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '300 feet' ],
            "Mordenkainen's Sword" => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Moonbeam' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Meteor Swarm' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '1 mile' ],
            "Melf's Minute Meteors" => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self' ],
            "Melf's Acid Arrow" => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '90 feet' ],
            'Mass Healing Word' => [ 'type' => '3rd-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => '60 feet' ],
            'Mass Heal' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Mass Cure Wounds' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Magic Missile' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Maelstrom' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Maddening Darkness' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Lightning Lure' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '15 feet' ],
            'Lightning Bolt' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (100-foot line)' ],
            'Light' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Touch' ],
            "Leomund's Tiny Hut" => [ 'type' => '3rd-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'evocation', 'range' => 'Self (10-foot-radius hemisphere)' ],
            "Jim's Magic Missile" => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Immolation' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '90 feet' ],
            'Ice Storm' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '300 feet' ],
            'Holy Weapon' => [ 'type' => '5th-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Touch' ],
            'Hellish Rebuke' => [ 'type' => '1st-level', 'time' => 'Reaction', 'school' => 'evocation', 'range' => '60 feet' ],
            'Healing Word' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => '60 feet' ],
            'Heal' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Hallow' => [ 'type' => '5th-level', 'time' => '24 Hours', 'school' => 'evocation', 'range' => 'Touch' ],
            'Gust of Wind' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (60-foot line)' ],
            'Guiding Bolt' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Green-Flame Blade' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '5 feet' ],
            'Gravity Sinkhole' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Gravity Fissure' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (100-foot line)' ],
            'Frostbite' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Frost Fingers' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (15-foot cone)' ],
            'Forcecage' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '100 feet' ],
            'Flame Strike' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Flame Blade' => [ 'type' => '2nd-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Self' ],
            'Fireball' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Fire Storm' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Fire Shield' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self' ],
            'Fire Bolt' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Faerie Fire' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Eldritch Blast' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Earthquake' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '500 feet' ],
            'Earth Tremor' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '10 feet' ],
            'Divine Word' => [ 'type' => '7th-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => '30 feet' ],
            'Divine Favor' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Self' ],
            'Destructive Wave' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (30-foot radius)' ],
            'Delayed Blast Fireball' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Daylight' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Dawn' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Darkness' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '60 feet' ],
            'Dark Star' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Dancing Lights' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Cure Wounds' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Touch' ],
            "Crusader's Mantle" => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (30-foot radius)' ],
            'Crown of Stars' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self' ],
            'Continual Flame' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Touch' ],
            'Contingency' => [ 'type' => '6th-level', 'time' => '10 Minutes', 'school' => 'evocation', 'range' => 'Self' ],
            'Cone of Cold' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (60-foot cone)' ],
            'Chromatic Orb' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '90 feet' ],
            'Chaos Bolt' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Chain Lightning' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '150 feet' ],
            'Burning Hands' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (15-foot cone)' ],
            'Branding Smite' => [ 'type' => '2nd-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Self' ],
            'Booming Blade' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'evocation', 'range' => '5 feet' ],
            'Blinding Smite' => [ 'type' => '3rd-level', 'time' => 'Bonus acn.', 'school' => 'evocation', 'range' => 'Self' ],
            'Blade Barrier' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '90 feet' ],
            "Bigby's Hand" => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '120 feet' ],
            'Aura of Vitality' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => 'Self (30-foot radius)' ],
            "Aganazzar's Scorcher" => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'evocation', 'range' => '30 feet' ],
            'Zone of Truth' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Vicious Mockery' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            "Tasha's Hideous Laughter" => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Synaptic Static' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '120 feet' ],
            'Suggestion' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Sleep' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '90 feet' ],
            'Psychic Scream' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '90 feet' ],
            'Power Word Stun' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Power Word Pain' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Power Word Kill' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            "Otto's Irresistible Dance" => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Motivational Speech' => [ 'type' => '3rd-level', 'time' => '1 Minute', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Modify Memory' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Mass Suggestion' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            "Jim's Glowing Coin" => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Incite Greed' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Hold Person' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Hold Monster' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '90 feet' ],
            'Hex' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'enchantment', 'range' => '90 feet' ],
            'Heroism' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => 'Touch' ],
            'Gift of Gab' => [ 'type' => '2nd-level', 'time' => 'Reaction', 'school' => 'enchantment', 'range' => 'Self' ],
            'Geas' => [ 'type' => '5th-level', 'time' => '1 Minute', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Friends' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'enchantment', 'range' => 'Self' ],
            'Feeblemind' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '150 feet' ],
            'Fast Friends' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Enthrall' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Enemies Abound' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '120 feet' ],
            'Encode Thoughts' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'enchantment', 'range' => 'Self' ],
            'Dominate Person' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Dominate Monster' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Dominate Beast' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Dissonant Whispers' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Crown of Madness' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '120 feet' ],
            'Confusion' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '90 feet' ],
            'Compulsion' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Compelled Duel' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Command' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Charm Person' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Charm Monster' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Catnap' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Calm Emotions' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Bless' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Bane' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Antipathy/Sympathy' => [ 'type' => '8th-level', 'time' => '1 Hour', 'school' => 'enchantment', 'range' => '60 feet' ],
            'Animal Messenger' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'Animal Friendship' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'enchantment', 'range' => '30 feet' ],
            'True Strike' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'divination', 'range' => '30 feet' ],
            'True Seeing' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'divination', 'range' => 'Touch' ],
            'Tongues' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'divination', 'range' => 'Touch' ],
            'Speak with Animals' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'See Invisibility' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Scrying' => [ 'type' => '5th-level', 'time' => '10 Minutes', 'school' => 'divination', 'range' => 'Self' ],
            "Rary's Telepathic Bond" => [ 'type' => '5th-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'divination', 'range' => '30 feet' ],
            'Mind Spike' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'divination', 'range' => '60 feet' ],
            'Locate Object' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Locate Creature' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Locate Animals or Plants' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Legend Lore' => [ 'type' => '5th-level', 'time' => '10 Minutes', 'school' => 'divination', 'range' => 'Self' ],
            'Identify' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Touch' ],
            "Hunter's Mark" => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'divination', 'range' => '90 feet' ],
            'Guidance' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'divination', 'range' => 'Touch' ],
            'Gift of Alacrity' => [ 'type' => '1st-level', 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Touch' ],
            "Fortune's Favor" => [ 'type' => '2nd-level', 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Touch' ],
            'Foresight' => [ 'type' => '9th-level', 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Touch' ],
            'Find Traps' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'divination', 'range' => '120 feet' ],
            'Find the Path' => [ 'type' => '6th-level', 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Self' ],
            'Divination' => [ 'type' => '4th-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Detect Thoughts' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Detect Poison and Disease' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Detect Magic' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Detect Evil and Good' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Contact Other Plane' => [ 'type' => '5th-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Self' ],
            'Comprehend Languages' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'divination', 'range' => 'Self' ],
            'Commune with Nature' => [ 'type' => '5th-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Self' ],
            'Commune' => [ 'type' => '5th-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Self' ],
            'Clairvoyance' => [ 'type' => '3rd-level', 'time' => '10 Minutes', 'school' => 'divination', 'range' => '1 mile' ],
            'Beast Sense' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'divination', 'range' => 'Touch' ],
            'Beast Bond' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'divination', 'range' => 'Touch' ],
            'Augury' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'divination', 'range' => 'Self' ],
            'Arcane Eye' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'divination', 'range' => '30 feet' ],
            'Wristpocket' => [ 'type' => '2nd-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Self' ],
            'Word of Recall' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '5 feet' ],
            'Wish' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Self' ],
            'Web' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Watery Sphere' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Wall of Thorns' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '120 feet' ],
            'Unseen Servant' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Tsunami' => [ 'type' => '8th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => 'Sight' ],
            'Tree Stride' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Self' ],
            'Transport via Plants' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '10 feet' ],
            'Tidal Wave' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '120 feet' ],
            'Thunder Step' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '90 feet' ],
            "Tenser's Floating Disk" => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => 'Action', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Temple of the Gods' => [ 'type' => '7th-level', 'time' => '1 Hour', 'school' => 'conjuration', 'range' => '120 feet' ],
            'Teleportation Circle' => [ 'type' => '5th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => '10 feet' ],
            'Teleport' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '10 feet' ],
            'Sword Burst' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'conjuration', 'range' => '5 feet' ],
            'Summon Lesser Demons' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Summon Greater Demon' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Storm of Vengeance' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Sight' ],
            'Stinking Cloud' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Steel Wind Strike' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Spirit Guardians' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Self (15-foot radius)' ],
            'Sleet Storm' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '150 feet' ],
            'Scatter' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Reality Break' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Produce Flame' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Self' ],
            'Poison Spray' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'conjuration', 'range' => '10 feet' ],
            'Plane Shift' => [ 'type' => '7th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Touch' ],
            'Planar Ally' => [ 'type' => '6th-level', 'time' => '10 Minutes', 'school' => 'conjuration', 'range' => '60 feet' ],
            "Mordenkainen's Magnificent Mansion" => [ 'type' => '7th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => '300 feet' ],
            "Mordenkainen's Faithful Hound" => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Misty Step' => [ 'type' => '2nd-level', 'time' => 'Bonus acn.', 'school' => 'conjuration', 'range' => 'Self' ],
            'Mighty Fortress' => [ 'type' => '8th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => '1 mile' ],
            'Maze' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Mage Hand' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'conjuration', 'range' => '30 feet' ],
            "Leomund's Secret Chest" => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Touch' ],
            'Insect Plague' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '300 feet' ],
            'Infestation' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Infernal Calling' => [ 'type' => '5th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Incendiary Cloud' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '150 feet' ],
            'Ice Knife' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Hunger of Hadar' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '150 feet' ],
            "Heroes' Feast" => [ 'type' => '6th-level', 'time' => '10 Minutes', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Healing Spirit' => [ 'type' => '2nd-level', 'time' => 'Bonus acn.', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Hail of Thorns' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'conjuration', 'range' => 'Self' ],
            'Guardian of Faith' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Grease' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Grasping Vine' => [ 'type' => '4th-level', 'time' => 'Bonus acn.', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Gate' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Fog Cloud' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '120 feet' ],
            'Flaming Sphere' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Find Steed' => [ 'type' => '2nd-level', 'time' => '10 Minutes', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Find Greater Steed' => [ 'type' => '4th-level', 'time' => '10 Minutes', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Find Familiar' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => '1 Hour', 'school' => 'conjuration', 'range' => '10 feet' ],
            'Far Step' => [ 'type' => '5th-level', 'time' => 'Bonus acn.', 'school' => 'conjuration', 'range' => 'Self' ],
            "Evard's Black Tentacles" => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Entangle' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Ensnaring Strike' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'conjuration', 'range' => 'Self' ],
            'Dust Devil' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            "Drawmij's Instant Summons" => [ 'type' => '6th-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'conjuration', 'range' => 'Touch' ],
            'Dimension Door' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '500 feet' ],
            'Demiplane' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Create Food and Water' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '30 feet' ],
            'Create Bonfire' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Conjure Woodland Beings' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Conjure Volley' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '150 feet' ],
            'Conjure Minor Elementals' => [ 'type' => '4th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Conjure Fey' => [ 'type' => '6th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Conjure Elemental' => [ 'type' => '5th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Conjure Celestial' => [ 'type' => '7th-level', 'time' => '1 Minute', 'school' => 'conjuration', 'range' => '90 feet' ],
            'Conjure Barrage' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Self (60-foot cone)' ],
            'Conjure Animals' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Cloudkill' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '120 feet' ],
            'Cloud of Daggers' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Call Lightning' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '120 feet' ],
            'Blade of Disaster' => [ 'type' => '9th-level', 'time' => 'Bonus acn.', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Arms of Hadar' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => 'Self (10-foot radius)' ],
            'Arcane Gate' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'conjuration', 'range' => '500 feet' ],
            'Acid Splash' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'conjuration', 'range' => '60 feet' ],
            'Warding Bond' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Symbol' => [ 'type' => '7th-level', 'time' => '1 Minute', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Stoneskin' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Snare' => [ 'type' => '1st-level', 'time' => '1 Minute', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Shield of Faith' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'abjuration', 'range' => '60 feet' ],
            'Shield' => [ 'type' => '1st-level', 'time' => 'Reaction', 'school' => 'abjuration', 'range' => 'Self' ],
            'Sanctuary' => [ 'type' => '1st-level', 'time' => 'Bonus acn.', 'school' => 'abjuration', 'range' => '30 feet' ],
            'Resistance' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Remove Curse' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Protection from Poison' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Protection from Evil and Good' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Protection from Energy' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Prismatic Wall' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => '60 feet' ],
            'Primordial Ward' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self' ],
            'Planar Binding' => [ 'type' => '5th-level', 'time' => '1 Hour', 'school' => 'abjuration', 'range' => '60 feet' ],
            'Pass without Trace' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self' ],
            'Nondetection' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            "Mordenkainen's Private Sanctum" => [ 'type' => '4th-level', 'time' => '10 Minutes', 'school' => 'abjuration', 'range' => '120 feet' ],
            'Mind Blank' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Magic Circle' => [ 'type' => '3rd-level', 'time' => '1 Minute', 'school' => 'abjuration', 'range' => '10 feet' ],
            'Mage Armor' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Lesser Restoration' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Invulnerability' => [ 'type' => '9th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self' ],
            'Imprisonment' => [ 'type' => '9th-level', 'time' => '1 Minute', 'school' => 'abjuration', 'range' => '30 feet' ],
            'Holy Aura' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self' ],
            'Guards and Wards' => [ 'type' => '6th-level', 'time' => '10 Minutes', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Greater Restoration' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Glyph of Warding' => [ 'type' => '3rd-level', 'time' => '1 Hour', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Globe of Invulnerability' => [ 'type' => '6th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self (10-foot radius)' ],
            'Freedom of Movement' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Forbiddance' => [ 'type' => '6th-level', 'is_ritual' => true, 'time' => '10 Minutes', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Druid Grove' => [ 'type' => '6th-level', 'time' => '10 Minutes', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Dispel Magic' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => '120 feet' ],
            'Dispel Evil and Good' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self' ],
            'Death Ward' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Counterspell' => [ 'type' => '3rd-level', 'time' => 'Reaction', 'school' => 'abjuration', 'range' => '60 feet' ],
            'Circle of Power' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self (30-foot radius)' ],
            'Ceremony' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => '1 Hour', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Blade Ward' => [ 'type' => 'cantrip', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self' ],
            'Beacon of Hope' => [ 'type' => '3rd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => '30 feet' ],
            'Banishment' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => '60 feet' ],
            'Banishing Smite' => [ 'type' => '5th-level', 'time' => 'Bonus acn.', 'school' => 'abjuration', 'range' => 'Self' ],
            'Aura of Purity' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self (30-foot radius)' ],
            'Aura of Life' => [ 'type' => '4th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self (30-foot radius)' ],
            'Armor of Agathys' => [ 'type' => '1st-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self' ],
            'Arcane Lock' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Touch' ],
            'Antimagic Field' => [ 'type' => '8th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self (10-foot radius)' ],
            'Antilife Shell' => [ 'type' => '5th-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => 'Self (10-foot radius)' ],
            'Alarm' => [ 'type' => '1st-level', 'is_ritual' => true, 'time' => '1 Minute', 'school' => 'abjuration', 'range' => '30 feet' ],
            'Aid' => [ 'type' => '2nd-level', 'time' => 'Action', 'school' => 'abjuration', 'range' => '30 feet' ],
            'Absorb Elements' => [ 'type' => '1st-level', 'time' => 'Reaction', 'school' => 'abjuration', 'range' => 'Self' ],
        ]);
    }

    public function createSchools(array $schools): void
    {
        collect($schools)->each(function(string $name) {
            $school = SpellSchool::factory()->create([ 'name' => $name ]);
            $this->set('spell-schools', $name, $school);
        });
    }

    public function createTypes(array $types): void
    {
        collect($types)->each(function(string $name) {
            $type = SpellType::factory()->create([ 'name' => $name ]);
            $this->set('spell-types', $name, $type);
        });
    }

    public function create(array $spells): void
    {
        collect($spells)->each(function(array $data, string $name) {
            $type = $this->get('spell-types', $data['type']);
            $school = $this->get('spell-schools', $data['school']);
            $spell = Spell::factory()->make([ 'name' => $name ]);
            $spell->school()->associate($school);
            $spell->type()->associate($type);
            $spell->save();
            $this->set('spells', $name, $spell);
        });
    }
}
